<a href="https://colab.research.google.com/github/minuuva/ds1002/blob/main/Minu_Choi_HW_07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [1]:
# Load pandas and the data
import pandas as pd
ride = pd.read_csv('ride_sharing.csv')
ride

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29 minutes,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [2]:
# show how many rows and columns are in this dataset
ride.shape
print(f'Number of rows: {ride.shape[0]}')
print(f'Number of columns:{ride.shape[1]}')

Number of rows: 25760
Number of columns:10

In [3]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)

ride['duration'] = ride['duration'].str.replace(' minutes', '')
ride['duration'] = ride['duration'].astype('int')

In [4]:
# Now display the datatypes in the updated dataframe
print(ride.dtypes)

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [5]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.

min_duration = ride['duration'].min()
max_duration = ride['duration'].max()

print(f'The shortest ride duration is {min_duration} minute.')
print(f'The longest ride duration is {max_duration} minutes.')

The shortest ride duration is 1 minute.
The longest ride duration is 1372 minutes.

In [6]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.

shortride = ride.query('duration <= 60')
shortride

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [7]:
# Now show both the min and max values of the duration column for your new dataset.
shortride_min_duration = shortride['duration'].min()
shortride_max_duration = shortride['duration'].max()

print(f'The shortest ride duration is {shortride_min_duration} minute.')
print(f'The longest ride duration is {shortride_max_duration} minutes.')

The shortest ride duration is 1 minute.
The longest ride duration is 60 minutes.

In [8]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.

shortride = shortride[shortride['tire_size'] == 26]
shortride

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
...,...,...,...,...,...,...,...,...,...,...
25750,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,4372,2,1994,Male,26
25751,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,5246,1,1995,Male,26
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26

In [9]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.

female_riders = sum(shortride['user_gender'] == 'Female')

print(f'The numer of female riders using the 26-inch tires for one hour or less is {female_riders}.')

The numer of female riders using the 26-inch tires for one hour or less is 2962.

2. Find the file `more-messy-data.csv` on Canvas and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [10]:
#loading the more-messy-data
messy = pd.read_csv('more-messy-data.csv')
messy

       id  sepal_length  sepal_width  petal_length petal_width     species
0       1           3.5          2.9           1.4         0.5   virginica
1       2           3.6          3.2           3.0         0.5      setosa
2       3           3.8          NaN           2.2         1.5      setosa
3       4           5.8          2.7           2.6         1.2   virginica
4       5           4.9          3.6           3.0         1.2   virginica
...   ...           ...          ...           ...         ...         ...
1311  412           NaN          3.6           2.9         0.5  Versicolor
1312  413           5.8          2.7           2.0         0.1  Versicolor
1313  414           3.3          3.7           1.3         2.8  Versicolor
1314  415           3.1          NaN           1.1         NaN  Versicolor
1315  416           4.3          2.5           1.3           1  Versicolor

[1316 rows x 6 columns]

In [11]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
print(messy.duplicated().sum())

287

In [12]:
# Next, remove all duplicate rows using Python.
messy = messy.drop_duplicates()
# I will print the number of duplicate rows in order to verify that the output is 0.
print(messy.duplicated().sum())

0

In [19]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.

# In my first attempt, I found that the data type for the columns 'sepal_length', 'sepal_width', 'petal_length'
# was float while 'petal_width' was an object. This prevented me from implementing numeric operations such as mean().


# I first created a list of columns that I aim to fill in NaN values with the mean of the column.
newcolumns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

# I initiated a for loop where for each column, I use pd.to_numeric() to convert the values in that column
# to a numeric type. The 'errors='coerce' that I learned in class, treats values that can't be converted
# to a number as NaN. This ensures that all columns will be numeric.
for column in newcolumns:
    messy[column] = pd.to_numeric(messy[column], errors='coerce')

for column in newcolumns:
    messy[column] = messy[column].fillna(messy[column].mean())

messy[newcolumns]

<ipython-input-19-37b06428f58c>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  messy[column] = pd.to_numeric(messy[column], errors='coerce')
<ipython-input-19-37b06428f58c>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  messy[column] = messy[column].fillna(messy[column].mean())

      sepal_length  sepal_width  petal_length  petal_width
0         3.500000      2.90000           1.4       0.5000
1         3.600000      3.20000           3.0       0.5000
2         3.800000      2.98876           2.2       1.5000
3         5.800000      2.70000           2.6       1.2000
4         4.900000      3.60000           3.0       1.2000
...            ...          ...           ...          ...
1311      4.522004      3.60000           2.9       0.5000
1312      5.800000      2.70000           2.0       0.1000
1313      3.300000      3.70000           1.3       2.8000
1314      3.100000      2.98876           1.1       1.5574
1315      4.300000      2.50000           1.3       1.0000

[1029 rows x 4 columns]

In [20]:
# Find any values in the dataframe that are still missing, and delete them.

messy_complete = messy.dropna()
messy_complete

       id  sepal_length  sepal_width  petal_length  petal_width     species
0       1      3.500000      2.90000           1.4       0.5000   virginica
1       2      3.600000      3.20000           3.0       0.5000      setosa
2       3      3.800000      2.98876           2.2       1.5000      setosa
3       4      5.800000      2.70000           2.6       1.2000   virginica
4       5      4.900000      3.60000           3.0       1.2000   virginica
...   ...           ...          ...           ...          ...         ...
1311  412      4.522004      3.60000           2.9       0.5000  Versicolor
1312  413      5.800000      2.70000           2.0       0.1000  Versicolor
1313  414      3.300000      3.70000           1.3       2.8000  Versicolor
1314  415      3.100000      2.98876           1.1       1.5574  Versicolor
1315  416      4.300000      2.50000           1.3       1.0000  Versicolor

[963 rows x 6 columns]

In [15]:
# How many different species are there?

# I decided to convert the 'species' column to a set as it  eliminates any duplicate elements.
# This set would then only contain unique elements.
species = set(messy_complete['species'])
number_of_species = len(species)
print(f"There are {number_of_species} different species.")

There are 10 different species.

In [16]:
# Clean up the 'species' variable so that there are exactly three different values.

# I will tackle this problem using a three step process.

# 1. Firstly, I will identify the unique 10 species. This is to understand which variations need to be corrected.
print(messy_complete['species'].unique())

# 2. Now that I have identified all the unique species names, I will replace each
# variation to one of the three: "Virginica", "Setosa", or "Versicolor"
# I will do this using a dictionary and the replace() function

replacements = {
    'virginica':'Virginica',
    'setosa':'Setosa',
    'setoso':'Setosa',
    'Viginica':'Virginica',
    'Virginia':'Virginica',
    'Setosan':'Setosa',
    'versicolor':'Versicolor'
}
messy_complete['species'] = messy_complete['species'].replace(replacements)

['virginica' 'setosa' 'Versicolor' 'setoso' 'Viginica' 'Virginia'
 'Virginica' 'Setosa' 'Setosan' 'versicolor']

<ipython-input-16-cab967854adf>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  messy_complete['species'] = messy_complete['species'].replace(replacements)

In [17]:
#3 The last step is a repetition of step 1 which verifies that there are only three unique species.
print(messy_complete['species'].unique())

['Virginica' 'Setosa' 'Versicolor']

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [ ]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'aabbbc'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
# print(type(re.match(exp,test)))

# uncomment this line if you want
# print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False